package:
  image:
    name: gradle:jdk11
  script:
    - gradle jar shadowjar
  artifacts:
    paths:
      - build/libs/keycloak-scim-1.0-SNAPSHOT.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all.jar
  only:
    - main
