name: Build keycloak-scim and release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: gradle build

    - name: Create Release with jar file
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "keycloak-scim release"
        files: |
          ./build/libs/*.jar
